

def load_vgg16(model, weights):
    model.get_layer('conv1').kernel.assign(weights['block1_conv1']['block1_conv1_W_1:0'][:])
    model.get_layer('conv1').bias.assign(weights['block1_conv1']['block1_conv1_b_1:0'][:])
    model.get_layer('conv1_1').kernel.assign(weights['block1_conv2']['block1_conv2_W_1:0'][:])
    model.get_layer('conv1_1').bias.assign(weights['block1_conv2']['block1_conv2_b_1:0'][:])
    model.get_layer('conv2').kernel.assign(weights['block2_conv1']['block2_conv1_W_1:0'][:])
    model.get_layer('conv2').bias.assign(weights['block2_conv1']['block2_conv1_b_1:0'][:])
    model.get_layer('conv2_1').kernel.assign(weights['block2_conv2']['block2_conv2_W_1:0'][:])
    model.get_layer('conv2_1').bias.assign(weights['block2_conv2']['block2_conv2_b_1:0'][:])
    model.get_layer('conv3').kernel.assign(weights['block3_conv1']['block3_conv1_W_1:0'][:])
    model.get_layer('conv3').bias.assign(weights['block3_conv1']['block3_conv1_b_1:0'][:])
    model.get_layer('conv3_1').kernel.assign(weights['block3_conv2']['block3_conv2_W_1:0'][:])
    model.get_layer('conv3_1').bias.assign(weights['block3_conv2']['block3_conv2_b_1:0'][:])
    model.get_layer('conv3_2').kernel.assign(weights['block3_conv3']['block3_conv3_W_1:0'][:])
    model.get_layer('conv3_2').bias.assign(weights['block3_conv3']['block3_conv3_b_1:0'][:])
    model.get_layer('conv4').kernel.assign(weights['block4_conv1']['block4_conv1_W_1:0'][:])
    model.get_layer('conv4').bias.assign(weights['block4_conv1']['block4_conv1_b_1:0'][:])
    model.get_layer('conv4_1').kernel.assign(weights['block4_conv2']['block4_conv2_W_1:0'][:])
    model.get_layer('conv4_1').bias.assign(weights['block4_conv2']['block4_conv2_b_1:0'][:])
    model.get_layer('conv4_2').kernel.assign(weights['block4_conv3']['block4_conv3_W_1:0'][:])
    model.get_layer('conv4_2').bias.assign(weights['block4_conv3']['block4_conv3_b_1:0'][:])
    model.get_layer('conv5').kernel.assign(weights['block5_conv1']['block5_conv1_W_1:0'][:])
    model.get_layer('conv5').bias.assign(weights['block5_conv1']['block5_conv1_b_1:0'][:])
    model.get_layer('conv5_1').kernel.assign(weights['block5_conv2']['block5_conv2_W_1:0'][:])
    model.get_layer('conv5_1').bias.assign(weights['block5_conv2']['block5_conv2_b_1:0'][:])
    model.get_layer('conv5_2').kernel.assign(weights['block5_conv3']['block5_conv3_W_1:0'][:])
    model.get_layer('conv5_2').bias.assign(weights['block5_conv3']['block5_conv3_b_1:0'][:])
    model.get_layer('fc1').kernel.assign(weights['fc1']['fc1_W_1:0'][:])
    model.get_layer('fc1').bias.assign(weights['fc1']['fc1_b_1:0'][:])
    model.get_layer('fc2').kernel.assign(weights['fc2']['fc2_W_1:0'][:])
    model.get_layer('fc2').bias.assign(weights['fc2']['fc2_b_1:0'][:])
    model.get_layer('predictions').kernel.assign(weights['predictions']['predictions_W_1:0'][:])
    model.get_layer('predictions').bias.assign(weights['predictions']['predictions_b_1:0'][:])
